name: dinov3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - decorator
    - ftfy # needed for dino.txt
    - glasbey
    - h5py
    - ipykernel
    - iopath
    - joblib
    - matplotlib
    - natsort
    - numpy
    - omegaconf
    - pandas
    - pillow
    - regex # needed for dino.txt
    - scipy
    - scikit-learn
    - scikit-learn-intelex
    - seaborn
    - submitit
    - termcolor
    - torch
    - torchmetrics
    - torchvision
